//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Personal {
    
    /// <summary>
    /// bannerContainer control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ClassicalSchoolManagement.design.Banner bannerContainer;
    
    /// <summary>
    /// DefaultMenuContent control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ClassicalSchoolManagement.design.Menu1 DefaultMenuContent;
    
    /// <summary>
    /// PersonalMenuContent control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ClassicalSchoolManagement.design.Menus.PersonalMenu PersonalMenuContent;
}
